# organize_live.yml v7.9
name: organize_live

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3,11,19 * * *'
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install aiohttp tqdm

      - name: Run organizer
        run: python m3u8_organizer.py --config config.json --rules-dir rules --manual-sources-dir sources_manual --generated-sources-dir sources_generated --remote-sources-file sources.txt --b config/blacklist.txt -f config/favorites.txt -o dist/live

      - name: Commit updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: auto update (v7.9)'
          commit_user_name: 'Waner-Bot'
          commit_user_email: 'waner-bot@users.noreply.github.com'
          push_options: '--force'
